### ISSUE TITLE
Explizite Schnittstellen

### ISSUE THREAD

**Issue by alexsuter** [wuethrich44/zusammenfassung-vsk#2]
Was versteht ihr unter explizite Schnittstellen? Bzw. wie würdet ihr das erklären.

Ihr habt das in jud.tex - unter Prinzipien.

Minimale Schnittstellen verstehe ich - möglichst wenig nach aussen öffentlich machen - möglichst wenige Parameter, Methoden usw..

**Comment by fabwu** [comment]
Keine Ahnung was damit gemeint ist. Folgendes steht ihn den Folien:

![unbenannt](https://cloud.githubusercontent.com/assets/6050639/5793394/35989d18-9f42-11e4-89af-036ad6299ed4.PNG)

**Comment by alexsuter** [comment]
wtf!
